name: Update the tables

# these are the listeners
# this action will run with workflow_dispatch meaning we can manually trigger it
# or we can trigger it every few hours using cron syntax
on:
  schedule:
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of the month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12)
    # │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday)
    # │ │ │ │ │
    # │ │ │ │ │
    # * * * * *
    - cron: '6,7 */2 * * *'
  workflow_dispatch:   

# summary is the unique id of the job
# runs-on makes a new linux vm to run the job
# permissions self explanatory
# machine has to check out the repo first
jobs:
  execute:
      runs-on: ubuntu-latest

      permissions:
        contents: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: 'stable' 

        - name: Run Go script
          working-directory: ./go
          run: go run .

          # Only commit and push if there are actual changes to avoid failing the job
        - name: Commit and push
          run: |
            git config --global user.name "guai guai[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git diff --quiet && git diff --staged --quiet || (git commit -m "Update README tables [skip ci]" && git push)