name: Update the tables

on:
  schedule:
    - cron: '6,37 * * * *'
  workflow_dispatch:   

jobs:
  execute:
      runs-on: ubuntu-latest

      permissions:
        contents: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 2  

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: 'stable' 

        - name: Run Go script
          working-directory: ./go
          run: go run .

          # Only commit and push if there are actual changes to avoid failing the job
          # merge the old ones so we dont clutter the logs
        - name: Commit and push
          run: |
            git config --global user.name "guai guai[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git pull --rebase --autostash

            git add -A

            if ! git diff --staged --quiet; then
              LAST_TITLE=$(git log -1 --pretty=%s)
              LAST_BODY=$(git log -1 --pretty=%b)

              if [ "$LAST_TITLE" = "Update README tables [skip ci]" ]; then
                if [[ "$LAST_BODY" =~ \#([0-9]+) ]]; then
                  COUNT=$((${BASH_REMATCH[1]} + 1))
                else
                  COUNT=2
                fi

                git commit --amend -m "Update README tables [skip ci]" -m "Updated README #${COUNT}"
                git push --force-with-lease
              else
                git commit -m "Update README tables [skip ci]" -m "Updated README #1"
                git push
              fi
            fi
