name: Update the tables

on:
  schedule:
    - cron: '6,7 */2 * * *'
  workflow_dispatch:   

jobs:
  execute:
      runs-on: ubuntu-latest

      permissions:
        contents: write

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 2  

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: 'stable' 

        - name: Run Go script
          working-directory: ./go
          run: go run .

          # Only commit and push if there are actual changes to avoid failing the job
          # merge the old ones so we dont clutter the logs
        - name: Commit and push
          run: |
            git config --global user.name "guai guai[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A

            if ! git diff --staged --quiet; then
              LAST_MSG=$(git log -1 --pretty=%s)

              if [[ "$LAST_MSG" == "Update README tables"* ]]; then
                
                if [[ "$LAST_MSG" =~ \#([0-9]+) ]]; then
                  COUNT=$((${BASH_REMATCH[1]} + 1))
                else
                  COUNT=1
                fi

                git commit --amend -m "Update README tables #${COUNT} [skip ci]"
                git push --force-with-lease
              else
                git commit -m "Update README tables [skip ci]"
                git push
              fi
            fi